# Generated by Django 3.2.7 on 2021-11-08 05:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('coordinate1', models.FloatField()),
                ('coordinate2', models.FloatField()),
                ('coordinate3', models.FloatField()),
                ('coordinate4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sumbnail', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('coordinate1', models.FloatField()),
                ('coordinate2', models.FloatField()),
                ('coordinate3', models.FloatField()),
                ('coordinate4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, null=True)),
                ('coordinate1', models.FloatField()),
                ('coordinate2', models.FloatField()),
                ('coordinate3', models.FloatField()),
                ('coordinate4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=20)),
                ('roll', models.CharField(max_length=50)),
                ('introduction', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100, null=True)),
                ('coordinate1', models.FloatField()),
                ('coordinate2', models.FloatField()),
                ('coordinate3', models.FloatField()),
                ('coordinate4', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('work_start_date', models.DateTimeField()),
                ('work_end_date', models.DateTimeField()),
                ('title', models.CharField(max_length=50)),
                ('sumbnail', models.ImageField(upload_to='images/')),
                ('content', models.TextField()),
            ],
        ),
    ]
