# Generated by Django 3.2.9 on 2021-12-12 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='introduction',
            field=models.CharField(max_length=300),
        ),
    ]
