# Generated by Django 3.2.10 on 2022-02-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mail', models.EmailField(max_length=254)),
                ('content', models.TextField(blank=True, max_length=4000)),
                ('application_file', models.FileField(blank=True, upload_to='media/%Y-%m-%d-%H-%M-%S')),
            ],
        ),
    ]
