# Generated by Django 3.2.9 on 2021-12-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0002_alter_profile_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='order',
            field=models.FloatField(default=0),
        ),
    ]
