# Generated by Django 3.2.10 on 2022-02-21 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0002_application_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
