# Generated by Django 3.2.9 on 2021-12-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0003_profile_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='link',
            new_name='facebook',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='comment',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='businessHour',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='document',
            field=models.CharField(default='null', max_length=4000),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='homepage',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='introduction',
            field=models.CharField(default='null', max_length=300),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='sumbnail',
            field=models.ImageField(default='../media/images/profile_default.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twiter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(max_length=1000),
        ),
    ]
