# Generated by Django 3.2.9 on 2021-12-18 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0004_auto_20211218_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='document',
            field=models.TextField(default='null', max_length=4000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.TextField(default='null', max_length=300),
        ),
    ]
