# Generated by Django 3.2.9 on 2021-12-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0005_auto_20211218_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumbnail', models.ImageField(default='../media/images/profile_default.jpeg', upload_to='images/')),
                ('image', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=50)),
                ('introduction', models.TextField(default='null', max_length=300)),
                ('businessHour', models.TextField(default='null', max_length=200)),
                ('document', models.TextField(default='null', max_length=4000)),
                ('homepage', models.CharField(max_length=100, null=True)),
                ('telephone', models.CharField(max_length=100, null=True)),
                ('instagram', models.CharField(max_length=100, null=True)),
                ('twiter', models.CharField(max_length=100, null=True)),
                ('facebook', models.CharField(max_length=100, null=True)),
                ('coordinate_pc_top', models.FloatField()),
                ('coordinate_pc_left', models.FloatField()),
                ('coordinate_mobile_top', models.FloatField()),
                ('coordinate_mobile_left', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='businessHour',
            field=models.TextField(default='null', max_length=200),
        ),
    ]
