# Generated by Django 3.2.9 on 2021-12-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0007_alter_restaurant_sample_sumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_sample',
            name='maplink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='document',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='homepage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='twiter',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
