# Generated by Django 3.2.9 on 2021-12-19 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0008_auto_20211219_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant_sample',
            old_name='twiter',
            new_name='twitter',
        ),
    ]
