# Generated by Django 3.2.9 on 2021-12-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0009_rename_twiter_restaurant_sample_twitter'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant_sample',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
