# Generated by Django 3.2.9 on 2021-12-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0012_auto_20211219_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant_sample',
            name='introduction',
            field=models.CharField(default='null', max_length=300),
        ),
    ]
