# Generated by Django 3.2.9 on 2021-12-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0013_alter_restaurant_sample_introduction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Restaurant_sample',
        ),
        migrations.RenameField(
            model_name='art',
            old_name='comment',
            new_name='sumbnail',
        ),
        migrations.RenameField(
            model_name='cat',
            old_name='comment',
            new_name='sumbnail',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='comment',
            new_name='sumbnail',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='link',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='twiter',
        ),
        migrations.AddField(
            model_name='art',
            name='apple_maplink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='art',
            name='document',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='art',
            name='google_maplink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='art',
            name='introduction',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='cat',
            name='document',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='cat',
            name='introduction',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hotel',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='apple_maplink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='businessHour',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='document',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AddField(
            model_name='hotel',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='google_maplink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='homepage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='introduction',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='hotel',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='hotel',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='apple_maplink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='google_maplink',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='twitter',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='businessHour',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='document',
            field=models.TextField(blank=True, max_length=4000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='homepage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='introduction',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sumbnail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='telephone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
