# Generated by Django 3.2.9 on 2021-12-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0014_auto_20211219_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant_sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumbnail', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=50)),
                ('introduction', models.CharField(blank=True, max_length=300)),
                ('businessHour', models.TextField(blank=True, max_length=200)),
                ('document', models.TextField(blank=True, max_length=4000)),
                ('homepage', models.CharField(blank=True, max_length=100)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('instagram', models.CharField(blank=True, max_length=100)),
                ('twitter', models.CharField(blank=True, max_length=100)),
                ('facebook', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('apple_maplink', models.CharField(blank=True, max_length=100)),
                ('google_maplink', models.CharField(blank=True, max_length=100)),
                ('coordinate_pc_top', models.FloatField()),
                ('coordinate_pc_left', models.FloatField()),
                ('coordinate_mobile_top', models.FloatField()),
                ('coordinate_mobile_left', models.FloatField()),
            ],
        ),
    ]
