# Generated by Django 3.2.9 on 2021-12-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0015_restaurant_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='art',
            name='sumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='cat',
            name='sumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='sumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='sumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='image',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='sumbnail',
            field=models.CharField(max_length=300),
        ),
    ]
