# Generated by Django 3.2.9 on 2021-12-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0016_auto_20211220_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('order', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(default='', max_length=300),
        ),
    ]
