# Generated by Django 3.2.9 on 2021-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0017_auto_20211220_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=300),
        ),
    ]
