# Generated by Django 3.2.9 on 2021-12-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0018_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='sumbnail',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='work',
            name='sumbnail',
            field=models.CharField(max_length=300),
        ),
    ]
