# Generated by Django 3.2.9 on 2021-12-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0020_auto_20211220_0251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
                ('order', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Sponsor_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.FloatField()),
            ],
        ),
    ]
