# Generated by Django 3.2.9 on 2021-12-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0021_sponsor_banner_sponsor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slideshow_pc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=300)),
                ('order', models.FloatField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Slideshow',
            new_name='Slideshow_mobile',
        ),
    ]
