# Generated by Django 3.2.10 on 2022-01-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0023_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='application_file',
            field=models.FileField(upload_to='usr/share/nginx/html/media/%Y-%m-%d-%H-%M-%S'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='terms_file',
            field=models.FileField(upload_to='usr/share/nginx/html/media/%Y-%m-%d-%H-%M-%S'),
        ),
    ]
