# Generated by Django 3.2.10 on 2022-01-20 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0024_auto_20220110_2349'),
        ('ogijima', '0024_rename_sumbnail_art_thumbnail_and_more'),
    ]

    operations = [
    ]
