# Generated by Django 4.0.1 on 2022-01-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0025_restaurant_and_hotel'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor_banner',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='sponsor_name',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
