# Generated by Django 3.2.10 on 2022-01-20 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0025_merge_20220120_1404'),
        ('ogijima', '0025_restaurant_and_hotel'),
    ]

    operations = [
    ]
