# Generated by Django 3.2.10 on 2022-01-26 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0026_merge_20220120_2344'),
        ('ogijima', '0026_sponsor_banner_link_sponsor_name_link'),
    ]

    operations = [
    ]
