# Generated by Django 3.2.10 on 2022-02-04 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0027_merge_20220127_0100'),
        ('ogijima', '0027_notification_external_link'),
    ]

    operations = [
    ]
