# Generated by Django 3.2.10 on 2022-02-11 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0028_merge_20220204_1643'),
        ('ogijima', '0028_work_for_calender'),
    ]

    operations = [
    ]
