# Generated by Django 4.0.1 on 2022-02-14 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0028_work_for_calender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='terms_file',
        ),
    ]
