# Generated by Django 3.2.10 on 2022-02-14 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0029_merge_0028_merge_20220204_1643_0028_work_for_calender'),
        ('ogijima', '0029_remove_contact_terms_file'),
    ]

    operations = [
    ]
