# Generated by Django 3.2.10 on 2022-02-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogijima', '0030_merge_20220215_0503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='terms_file',
        ),
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='art',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='cat',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='application_file',
            field=models.FileField(blank=True, upload_to='media/%Y-%m-%d-%H-%M-%S'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant_and_hotel',
            name='image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='restaurant_and_hotel',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='image',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='restaurant_sample',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='slideshow_mobile',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='slideshow_pc',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='sponsor_banner',
            name='image',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='work',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
    ]
